/**
 * Core types for ASAKAA Kanban Board
 * @module types
 */

// ============================================================================
// CORE DATA TYPES
// ============================================================================

/**
 * Priority levels for cards
 */
export type Priority = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT'

/**
 * Card status types
 */
export type CardStatus = 'TODO' | 'IN_PROGRESS' | 'REVIEW' | 'DONE' | 'BLOCKED'

/**
 * Card entity
 * Represents a single task/item in the Kanban board
 */
export interface Card {
  /** Unique identifier */
  id: string
  /** Card title (required) */
  title: string
  /** Card description (optional) */
  description?: string
  /** Lexicographic position within column (for ordering) */
  position: number
  /** Parent column ID */
  columnId: string

  // Optional metadata (user can extend)
  /** Priority level */
  priority?: Priority
  /** Assigned user ID (legacy - use assignedUserIds) */
  assigneeId?: string
  /** Assigned user IDs (multiple users) */
  assignedUserIds?: string[]
  /** Tags/labels */
  labels?: string[]
  /** Due date (legacy - use startDate/endDate) */
  dueDate?: Date | string
  /** Date range - start date */
  startDate?: Date | string
  /** Date range - end date */
  endDate?: Date | string
  /** Task dependencies (card IDs this task depends on) */
  dependencies?: string[]
  /** Estimated time (in hours) */
  estimatedTime?: number
  /** Custom metadata */
  metadata?: Record<string, any>

  // Timestamps
  createdAt?: Date | string
  updatedAt?: Date | string
}

/**
 * Column entity
 * Represents a stage/status in the workflow
 */
export interface Column {
  /** Unique identifier */
  id: string
  /** Column title */
  title: string
  /** Lexicographic position (for ordering columns) */
  position: number
  /** Array of card IDs in this column */
  cardIds: string[]

  // Optional configuration
  /** Work-in-progress limit */
  wipLimit?: number
  /** Color for visual distinction */
  color?: string
  /** Custom metadata */
  metadata?: Record<string, any>

  // Timestamps
  createdAt?: Date | string
  updatedAt?: Date | string
}

/**
 * Board entity
 * Top-level container for the Kanban board
 */
export interface Board {
  /** Unique identifier */
  id: string
  /** Board title */
  title?: string
  /** Array of columns */
  columns: Column[]
  /** Array of all cards */
  cards: Card[]

  // Optional metadata
  metadata?: Record<string, any>
}

// ============================================================================
// CALLBACK TYPES
// ============================================================================

/**
 * Callbacks for board operations
 * These allow the library consumer to persist changes
 */
export interface BoardCallbacks {
  /** Called when a card is moved to a different position/column */
  onCardMove?: (
    cardId: string,
    targetColumnId: string,
    position: number
  ) => void | Promise<void>

  /** Called when card properties are updated */
  onCardUpdate?: (
    cardId: string,
    updates: Partial<Card>
  ) => void | Promise<void>

  /** Called when a new card is created */
  onCardCreate?: (
    card: Omit<Card, 'id'>
  ) => void | Promise<void>

  /** Called when a card is deleted */
  onCardDelete?: (cardId: string) => void | Promise<void>

  /** Called when a new column is created */
  onColumnCreate?: (
    column: Omit<Column, 'id' | 'cardIds'>
  ) => void | Promise<void>

  /** Called when column properties are updated */
  onColumnUpdate?: (
    columnId: string,
    updates: Partial<Column>
  ) => void | Promise<void>

  /** Called when a column is deleted */
  onColumnDelete?: (columnId: string) => void | Promise<void>

  /** Called when columns are reordered */
  onColumnReorder?: (
    columnId: string,
    newPosition: number
  ) => void | Promise<void>
}

// ============================================================================
// AI TYPES (Optional features)
// ============================================================================

/**
 * Insight types generated by AI
 */
export type InsightType =
  | 'RISK_DELAY'          // Risk of project delay
  | 'RISK_OVERLOAD'       // Team member overload
  | 'RISK_BLOCKER'        // Blocking dependency
  | 'OPPORTUNITY'         // Optimization opportunity
  | 'SUGGESTION'          // General suggestion

/**
 * Severity levels for insights
 */
export type InsightSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'

/**
 * AI-generated insight about the board state
 */
export interface Insight {
  /** Unique identifier */
  id?: string
  /** Type of insight */
  type: InsightType
  /** Severity level */
  severity: InsightSeverity
  /** Human-readable title */
  title: string
  /** Detailed description */
  description: string
  /** AI confidence score (0-1) */
  confidence: number
  /** Suggested action to take */
  suggestedAction?: string
  /** Related card IDs */
  relatedCardIds?: string[]
  /** Related column IDs */
  relatedColumnIds?: string[]
  /** Timestamp */
  timestamp?: Date | string
}

/**
 * Result of AI assignee suggestion
 */
export interface AssigneeSuggestion {
  /** Suggested user ID */
  userId: string
  /** Confidence score (0-1) */
  confidence: number
  /** Reasoning for suggestion */
  reasoning: string
}

/**
 * Result of AI plan generation
 */
export interface GeneratedPlan {
  /** Generated columns */
  columns: Omit<Column, 'id'>[]
  /** Generated cards */
  cards: Omit<Card, 'id'>[]
  /** Explanation of the plan */
  explanation?: string
}

/**
 * AI callbacks (optional)
 * Consumer provides these if they want AI features
 */
export interface AICallbacks {
  /** Generate a complete board plan from a text prompt */
  onGeneratePlan?: (prompt: string) => Promise<GeneratedPlan>

  /** Suggest best assignee for a card */
  onSuggestAssignee?: (card: Card) => Promise<AssigneeSuggestion>

  /** Predict risks and opportunities based on board state */
  onPredictRisks?: (boardState: Board) => Promise<Insight[]>

  /** Generate subtasks for a card */
  onGenerateSubtasks?: (card: Card) => Promise<Omit<Card, 'id'>[]>

  /** Estimate effort for a card */
  onEstimateEffort?: (card: Card) => Promise<{ hours: number, confidence: number }>
}

// ============================================================================
// COMPONENT PROPS TYPES
// ============================================================================

/**
 * Configuration options for the Kanban board
 */
export interface BoardConfig {
  /** Enable virtualization (auto-enabled if >100 cards) */
  enableVirtualization?: boolean
  /** Enable AI features */
  enableAI?: boolean
  /** Animation duration in milliseconds */
  animationDuration?: number
  /** Fixed column width in pixels */
  columnWidth?: number
  /** Estimated card height for virtualization */
  cardHeight?: number
  /** Enable keyboard shortcuts */
  enableKeyboardShortcuts?: boolean
  /** Show card count in column headers */
  showCardCount?: boolean
  /** Show WIP limits */
  showWipLimits?: boolean
  /** Enable column collapsing */
  enableCollapsible?: boolean
  /** Maximum cards to display per column before showing "show more" */
  maxCardsPerColumn?: number
}

/**
 * Render props for customization
 */
export interface RenderProps {
  /** Custom card renderer */
  renderCard?: (card: Card) => React.ReactNode
  /** Custom column renderer */
  renderColumn?: (column: Column, cards: Card[]) => React.ReactNode
  /** Custom card overlay during drag */
  renderCardOverlay?: (card: Card) => React.ReactNode
  /** Custom column header */
  renderColumnHeader?: (column: Column, cardCount: number) => React.ReactNode
  /** Custom empty state */
  renderEmptyState?: (column: Column) => React.ReactNode
}

/**
 * User entity for assignment
 */
export interface User {
  id: string
  name: string
  initials: string
  color: string
  avatar?: string
}

/**
 * Main KanbanBoard component props
 */
export interface KanbanBoardProps {
  /** Board data (controlled) */
  board: Board

  /** Callbacks for mutations */
  callbacks: BoardCallbacks

  /** AI callbacks (optional) */
  aiCallbacks?: AICallbacks

  /** Card click handler */
  onCardClick?: (card: Card) => void

  /** Render customization */
  renderProps?: RenderProps

  /** Configuration */
  config?: BoardConfig

  /** Available users for assignment */
  availableUsers?: User[]

  /** Custom CSS class */
  className?: string

  /** Custom inline styles */
  style?: React.CSSProperties

  /** Loading state */
  isLoading?: boolean

  /** Error state */
  error?: Error | string
}

// ============================================================================
// DRAG & DROP TYPES
// ============================================================================

/**
 * Drag event data
 */
export interface DragData {
  /** Card being dragged */
  card: Card
  /** Source column ID */
  sourceColumnId: string
  /** Source position */
  sourcePosition: number
}

/**
 * Drop event data
 */
export interface DropData {
  /** Card being dropped */
  card: Card
  /** Target column ID */
  targetColumnId: string
  /** Target position */
  targetPosition: number
  /** Source column ID */
  sourceColumnId: string
}

// ============================================================================
// FILTER & SORT TYPES
// ============================================================================

/**
 * Filter criteria for cards
 */
export interface CardFilter {
  /** Filter by assignee */
  assigneeIds?: string[]
  /** Filter by priority */
  priorities?: Priority[]
  /** Filter by labels */
  labels?: string[]
  /** Search in title/description */
  search?: string
  /** Filter by date range */
  dateRange?: {
    start: Date | string
    end: Date | string
  }
}

/**
 * Sort options for cards
 */
export type CardSortKey =
  | 'position'
  | 'priority'
  | 'dueDate'
  | 'createdAt'
  | 'title'

export interface CardSort {
  key: CardSortKey
  direction: 'asc' | 'desc'
}

// ============================================================================
// STATE TYPES
// ============================================================================

/**
 * Internal state for drag operations
 */
export interface DragState {
  isDragging: boolean
  draggedCardId: string | null
  sourceColumnId: string | null
  targetColumnId: string | null
}

/**
 * Selection state for multi-select
 */
export interface SelectionState {
  selectedCardIds: string[]
  lastSelectedCardId: string | null
}

// ============================================================================
// COMMENTS & ACTIVITY TYPES
// ============================================================================

/**
 * Comment on a card
 */
export interface Comment {
  /** Unique identifier */
  id: string
  /** Card ID */
  cardId: string
  /** Author user ID */
  authorId: string
  /** Comment content */
  content: string
  /** Timestamp */
  createdAt: Date | string
  /** Last update timestamp */
  updatedAt?: Date | string
  /** Mentions (user IDs) */
  mentions?: string[]
}

/**
 * Activity log entry types
 */
export type ActivityType =
  | 'CARD_CREATED'
  | 'CARD_UPDATED'
  | 'CARD_MOVED'
  | 'CARD_DELETED'
  | 'COMMENT_ADDED'
  | 'USER_ASSIGNED'
  | 'USER_UNASSIGNED'
  | 'PRIORITY_CHANGED'
  | 'DUE_DATE_CHANGED'
  | 'LABEL_ADDED'
  | 'LABEL_REMOVED'
  | 'DEPENDENCY_ADDED'
  | 'DEPENDENCY_REMOVED'

/**
 * Activity log entry
 */
export interface Activity {
  /** Unique identifier */
  id: string
  /** Activity type */
  type: ActivityType
  /** Card ID */
  cardId: string
  /** User who performed the action */
  userId: string
  /** Timestamp */
  timestamp: Date | string
  /** Previous value (for updates) */
  previousValue?: any
  /** New value (for updates) */
  newValue?: any
  /** Additional metadata */
  metadata?: Record<string, any>
}

// ============================================================================
// UTILITY TYPES
// ============================================================================

/**
 * Deep partial - makes all nested properties optional
 */
export type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P]
}

/**
 * Omit multiple keys at once
 */
export type OmitMultiple<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>

/**
 * Extract callback function type
 */
export type CallbackFn<T extends (...args: any[]) => any> = T extends (
  ...args: infer P
) => infer R
  ? (...args: P) => R
  : never
